EQLIB_VAR BOOL g_Loaded;
EQLIB_VAR DWORD ThreadID;

EQLIB_VAR HMODULE ghModule;
EQLIB_VAR HINSTANCE ghInstance;
EQLIB_VAR BOOL gbEQWLoaded;
EQLIB_VAR PHOTKEY pHotkey;
EQLIB_VAR BOOL gbUnload;
EQLIB_VAR DWORD gpHook;
EQLIB_VAR PMACROBLOCK gMacroBlock;
EQLIB_VAR PMACROSTACK gMacroStack;
EQLIB_VAR PEVENTSTACK gEventStack;
EQLIB_VAR PMACROBLOCK gEventFunc[NUM_EVENTS];
EQLIB_VAR UCHAR gLastFind;
EQLIB_VAR BOOL gInClick;
EQLIB_VAR DOUBLE gZFilter;
EQLIB_VAR DOUBLE gFaceAngle;
EQLIB_VAR DOUBLE gLookAngle;
EQLIB_VAR PVARSTRINGS gMacroStr;
EQLIB_VAR PVARARRAYS gArray;
EQLIB_VAR CHAR gszEQPath[MAX_STRING];
EQLIB_VAR CHAR gszMacroPath[MAX_STRING];
EQLIB_VAR CHAR gszVersion[MAX_STRING];
EQLIB_VAR CHAR gszLogPath[MAX_STRING];
EQLIB_VAR CHAR gszINIPath[MAX_STRING];
EQLIB_VAR CHAR gszINIFilename[MAX_STRING];
EQLIB_VAR CHAR gszINIMQchat[MAX_STRING];
EQLIB_VAR CHAR gszItemDB[MAX_STRING];
EQLIB_VAR CHAR gszMacroName[MAX_STRING];
EQLIB_VAR CHAR szLastCommand[MAX_STRING];
EQLIB_VAR DWORD gEventChat;
EQLIB_VAR DWORD gRunning;
EQLIB_VAR BOOL gbMoving;
EQLIB_VAR DWORD gMaxTurbo;

EQLIB_VAR BOOL gZoning;
EQLIB_VAR BOOL WereWeZoning;
EQLIB_VAR BOOL gbInDInput;
EQLIB_VAR BOOL gbInDState;
EQLIB_VAR BOOL gbInDAcquire;
EQLIB_VAR BOOL gbInChat;
EQLIB_VAR BOOL gFilterSkillsAll;
EQLIB_VAR BOOL gFilterSkillsIncrease;
EQLIB_VAR BOOL gFilterTarget;
EQLIB_VAR BOOL gFilterDebug;
EQLIB_VAR BOOL gFilterMoney;
EQLIB_VAR BOOL gFilterFood;
EQLIB_VAR DWORD gUseMQChatWnd;
EQLIB_VAR BOOL gFilterMacro;
EQLIB_VAR BOOL gFilterEncumber;
EQLIB_VAR BOOL gFilterCustom;
EQLIB_VAR BOOL gSpewToFile;
EQLIB_VAR BOOL gbDoAutoRun;
EQLIB_VAR BOOL gMQPauseOnChat;
EQLIB_VAR BOOL gKeepKeys;
EQLIB_VAR SWHOFILTER gFilterSWho;

EQLIB_VAR DOUBLE DegToRad;
EQLIB_VAR DOUBLE PI;


EQLIB_VAR PKEYPRESS gKeyStack;
EQLIB_VAR PTIMER gTimer;
EQLIB_VAR LONG gDelay;
EQLIB_VAR PALERTLIST gpAlertList;
EQLIB_VAR BOOL gMacroPause;
EQLIB_VAR SPAWNINFO EnviroTarget;
EQLIB_VAR ACTORINFO EnviroActor;
EQLIB_VAR PGROUNDITEM pGroundTarget;
EQLIB_VAR SPAWNINFO DoorEnviroTarget;
EQLIB_VAR PDOOR pDoorTarget;
EQLIB_VAR PITEMDB gItemDB;
EQLIB_VAR BOOL bRunNextCommand;
EQLIB_VAR BOOL gTurbo;
EQLIB_VAR PDEFINE pDefines;
EQLIB_VAR PEVENTLIST pEventList;
EQLIB_VAR CHAR gLastFindSlot[MAX_STRING];
EQLIB_VAR CHAR gLastError[MAX_STRING];
EQLIB_VAR HWND ghWnd;
EQLIB_VAR PFILTER gpFilters;

EQLIB_VAR BOOL g_bInDXMouse;
EQLIB_VAR PMOUSESPOOF gMouseData;

EQLIB_VAR DIKEYID gDiKeyID[];


EQLIB_VAR DWORD ManaGained;
EQLIB_VAR DWORD HealthGained;





EQLIB_VAR DWORD EQADDR_MAXMANA;
EQLIB_VAR DWORD EQADDR_COMMANDS;
EQLIB_VAR DWORD EQADDR_MEMCHECK;
EQLIB_VAR DWORD EQADDR_MEMCHECK2;
EQLIB_VAR DWORD EQADDR_MEMCHECKADDR1;
EQLIB_VAR DWORD EQADDR_MEMCHECKADDR2;
EQLIB_VAR DWORD EQADDR_MEMCHECK3;
EQLIB_VAR PCHAR EQADDR_SERVERHOST;
EQLIB_VAR PCHAR EQADDR_SERVERNAME;
EQLIB_VAR PCHAR *EQADDR_ACTIVEMERCHANT;
EQLIB_VAR PCHAR *EQADDR_ACTIVECORPSE;
EQLIB_VAR PPACKLOC EQADDR_PACKLOCS;
EQLIB_VAR DWORD EQADDR_ITEMDISPLAYSETITEM; 
EQLIB_VAR DWORD EQADDR_CXSTRAPPEND; 
EQLIB_VAR DWORD EQADDR_CXSTRSET; 
EQLIB_VAR DWORD EQADDR_HWND;

EQLIB_VAR PCMDLIST EQADDR_CMDLIST;

EQLIB_VAR PBYTE EQADDR_ATTACK;
EQLIB_VAR PBYTE EQADDR_NOTINCHATMODE;
EQLIB_VAR DWORD EQADDR_ZONING;
EQLIB_VAR PZONELIST **EQADDR_ZONELIST;
EQLIB_VAR PSPAWNINFO *EQADDR_SPAWNLIST;
EQLIB_VAR PSPAWNINFO *EQADDR_SPAWNTAIL;
EQLIB_VAR PSPAWNINFO *EQADDR_CHAR;
EQLIB_VAR PCHARINFO *EQADDR_CHAR_INFO;
EQLIB_VAR PSPAWNINFO *EQADDR_TARGET;
EQLIB_VAR PCHAR EQADDR_LASTTELL;
EQLIB_VAR PGROUNDITEM *EQADDR_ITEMS;
EQLIB_VAR _SPELLPOINTER** EQADDR_SPELLS;
EQLIB_VAR PSPAWNINFO *EQADDR_GROUP;
EQLIB_VAR PBYTE EQADDR_GROUPCOUNT;
EQLIB_VAR PVOID EQADDR_GWORLD;
EQLIB_VAR PDOORTABLE *EQADDR_DOORS;
EQLIB_VAR DWORD EQADDR_CLSITEMS;
EQLIB_VAR DWORD EQADDR_CLSSPAWNS;
EQLIB_VAR DWORD EQADDR_GUILDLIST;
EQLIB_VAR PDWORD EQADDR_DOABILITYLIST;
EQLIB_VAR PBYTE EQADDR_DOABILITYAVAILABLE;
EQLIB_VAR DWORD EQADDR_CASTSPELL;
EQLIB_VAR DWORD EQADDR_WRITEMAPFILE;
EQLIB_VAR DWORD EQADDR_CLEANUI;
EQLIB_VAR DWORD EQADDR_RCLICKTARGET;
EQLIB_VAR DWORD EQADDR_LCLICKTARGET;
EQLIB_VAR DWORD *EQADDR_CLSMAINNEWUI;
EQLIB_VAR DWORD *EQADDR_CLASSGIVEWND;
EQLIB_VAR PEQNOTESWINDOW* EQADDR_CLASSNOTESWND;
EQLIB_VAR DWORD *EQADDR_CLASSDISPLAYOBJECT;
EQLIB_VAR DWORD *EQADDR_CLASSBANKWND;

EQLIB_VAR PBYTE EQADDR_ENCRYPTPAD;
EQLIB_VAR PBYTE EQADDR_ENCRYPTPAD2;
EQLIB_VAR PBYTE EQADDR_ENCRYPTPAD3;
EQLIB_VAR PSPELLFAVORITE EQADDR_SPELLFAVORITES;

EQLIB_VAR PMOUSEINFO EQADDR_MOUSE;
EQLIB_VAR PMOUSECLICK EQADDR_MOUSECLICK;

EQLIB_VAR DWORD EQADDR_DIMAIN;
EQLIB_VAR IDirectInputDevice8A **EQADDR_DIKEYBOARD;
EQLIB_VAR IDirectInputDevice8A **EQADDR_DIMOUSE;

EQLIB_VAR DWORD *EQADDR_SPELLBOOKWND;
EQLIB_VAR DWORD *EQADDR_CLASSMERCHWND;
EQLIB_VAR DWORD *EQADDR_CLASSTEXTUREANIMATION;
EQLIB_VAR DWORD *EQADDR_INVENTORYWND;
EQLIB_VAR DWORD *EQADDR_CLASSCASTSPELLWND;
EQLIB_VAR DWORD *EQADDR_CLASSHOTBUTTONWND;
EQLIB_VAR DWORD *EQADDR_CASTINGWND;
EQLIB_VAR DWORD *EQADDR_LOOTWND;
EQLIB_VAR DWORD *EQADDR_CLASSMAPWND;
EQLIB_VAR DWORD EQADDR_GETFOCUSCASTINGTIMEMODIFIER;
EQLIB_VAR DWORD EQADDR_GETAACASTINGTIMEMODIFIER;
EQLIB_VAR PEQ_CONTAINERWND_MANAGER *EQADDR_CLASSCONTAINERMGR;
EQLIB_VAR DWORD *EQADDR_SLOTLIST;
EQLIB_VAR PZONEINFO EQADDR_ZONEINFO;

EQLIB_VAR DWORD *EQADDR_CHATMANAGER;
EQLIB_VAR DWORD EQADDR_CCHATMANAGERGETRGBAFROMINDEX;
EQLIB_VAR DWORD EQADDR_CXSTRCONSTRUCTOR;
EQLIB_VAR DWORD EQADDR_CXSTRFREE;
EQLIB_VAR DWORD EQADDR_APPENDSTML;
EQLIB_VAR DWORD EQADDR_CONVERTITEMTAGS;
EQLIB_VAR DWORD EQADDR_GETITEMLINKHASH;
EQLIB_VAR DWORD EQADDR_CCHATWINDOWCONSTRUCTOR;
EQLIB_VAR DWORD EQADDR_CHATMANAGERINITCONTEXTMENU;
EQLIB_VAR DWORD EQADDR_GETNUMBANKSLOTS;

EQLIB_VAR DWORD EQADDR_GETCURHP;
EQLIB_VAR DWORD EQADDR_GETMAXHP;

EQLIB_VAR DWORD EQADDR_EQLABELS;


EQLIB_VAR BOOL gMouseLeftClickInProgress;
EQLIB_VAR BOOL gMouseRightClickInProgress;
EQLIB_VAR BOOL bDetMouse;

// ***************************************************************************
// String arrays
// ***************************************************************************
EQLIB_VAR PCHAR szHeading[];
EQLIB_VAR PCHAR szHeadingShort[];
EQLIB_VAR PCHAR szSize[];
EQLIB_VAR PCHAR szSpawnType[];
EQLIB_VAR PCHAR szGuildStatus[];
EQLIB_VAR PCHAR szGender[];
EQLIB_VAR PCHAR szDeityTeam[];
EQLIB_VAR PCHAR szLights[];
EQLIB_VAR BYTE LightBrightness[];
EQLIB_VAR PCHAR szSkills[];
EQLIB_VAR PCHAR szCombineTypes[];
EQLIB_VAR PCHAR szItemTypes[];

EQLIB_VAR PCHAR szWornLoc[];


EQLIB_VAR fEQCommand         cmdHelp;
EQLIB_VAR fEQCommand         cmdWho;
EQLIB_VAR fEQCommand         cmdWhoTarget;
EQLIB_VAR fEQCommand         cmdLocation;
EQLIB_VAR fEQCommand         cmdFace;
EQLIB_VAR fEQCommand         cmdTarget;
EQLIB_VAR fEQCommand         cmdCharInfo;
EQLIB_VAR fEQCommand         cmdFilter;
EQLIB_VAR fEQCommand         cmdDoAbility;
EQLIB_VAR fEQCommand         cmdCast;
EQLIB_VAR fEQWriteChatColor  EQWriteChatColor;
EQLIB_VAR fEQGetStringByID   GetRaceByID;
EQLIB_VAR fEQGetStringByID   GetClassByID;
EQLIB_VAR fEQGetStringByID   GetDeityByID;
EQLIB_VAR fEQGetStringByID   GetBodyTypeByID;
EQLIB_VAR fEQScreenItem      ScreenItem;
EQLIB_VAR fEQScreenSpawn     ScreenSpawn;
EQLIB_VAR fEQNewUIINI        NewUIINI;
EQLIB_VAR fEQLoadSpells      cmdLoadSpells;
EQLIB_VAR fEQMemSpell        cmdMemSpell;
EQLIB_VAR fEQSelectItem      cmdSelectItem;
EQLIB_VAR fEQBuyItem         cmdBuyItem;
EQLIB_VAR fEQSellItem        cmdSellItem;
EQLIB_VAR fEQProcGameEvts    ProcessGameEvents;
EQLIB_VAR fEQSendMessage     send_message;

EQLIB_VAR PCHAR szItemName[];
EQLIB_VAR PCHAR szItemName4xx[];

EQLIB_VAR PALIAS pAliases;
EQLIB_VAR PMQCOMMAND pCommands;
EQLIB_VAR PMQPLUGIN pPlugins;