/*
 * MacroQuest: The extension platform for EverQuest
 * Copyright (C) 2002-present MacroQuest Authors
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 2, as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

"3D Realms",
"5th Cell",
"17-Bit",
"21st Street",
"343 Industries",
"704Games",
"Action Button",
"Activision Blizzard",
"Adscape",
"Aeria",
"Agetec",
"Aksys",
"Akupara",
"Amazon",
"American Sammy",
"Analogue",
"Annapurna",
"The Ant Commandos",
"Arcade1Up",
"Arcen",
"Areae",
"ArenaNet",
"Armor",
"Artificial",
"Artix",
"Artworx",
"Ascendant",
"Atari",
"Atlus USA",
"Autumn",
"Avatar Reality",
"Ayeah",
"Babaroga",
"Basilisk",
"Beamable",
"The Behemoth",
"Bend",
"Big Finish",
"Big Fish",
"Black Isle",
"Blendo",
"Blizzard Albany",
"Blizzard",
"Bolt",
"Boss Fight",
"Built",
"Bungie",
"Callisto",
"Campo Santo",
"Celeris",
"Cellufun",
"Chair",
"Chartboost",
"Chromatic",
"Cinematronics",
"Cipher Prime",
"Conspiracy",
"Coresoft",
"Cosmi",
"Crate",
"Creat",
"Creative Capers",
"Critical Gameplay",
"Cryptic",
"Crystal Dynamics",
"Curse LLC",
"Cyan Worlds",
"Darwin 3D",
"Davka",
"Daybreak Game Company",
"Deck Nine",
"Dejobaan",
"Delta Tao",
"Demiurge",
"DigiFX",
"Digital Cafe",
"Digital Eel",
"Double Aught",
"DoubleBear",
"DreamRift",
"Edge",
"Electronic Arts",
"Elsinore Multimedia",
"Empty Clip",
"Epic",
"Epicenter",
"Exakt",
"Exis",
"Factor 5",
"Fantasoft",
"Fantasy Flight",
"Fig",
"Filament",
"Finji",
"Fire Maple",
"First Star",
"Flying Tiger",
"Fox Digital",
"Freeverse Inc.",
"FreshGames",
"Fujisankei",
"Fullbright",
"Gabriel",
"Gaikai",
"Game Refuge",
"Game Titan",
"Gamecaster",
"GameHouse",
"Gamenauts",
"GameSamba",
"GameSim",
"GarageGames",
"Ghost Story",
"Global VR",
"GlyphX",
"Gravity",
"Green Throttle",
"Grey Dog",
"Grove Street",
"Grumpyface",
"Guild",
"Gun",
"Hanaho",
"Handheld",
"Hangar 13",
"Harebrained Schemes",
"Harmonix",
"Hayden Book",
"Heart Machine",
"Heavy Iron",
"HeR",
"Heuristic Park",
"Hi-Rez",
"Hidden City",
"Hidden Path",
"High Impact",
"High Moon",
"High Voltage",
"Himalaya",
"HipSoft",
"Hitcents",
"Holistic Design",
"Holy Wow",
"Humble Bundle",
"The Iconfactory",
"IEntertainment Network",
"IllFonic",
"Image Space",
"Imangi",
"Incredible",
"Infamous Quests",
"Inland",
"Interplay Discovery",
"Iron Galaxy",
"Iron Realms",
"Island Officials",
"Isotope 244",
"Jackbox",
"Jakks Pacific",
"Jam City",
"Jellyvision",
"Jump Shot Media",
"JumpStart",
"JV",
"Kabam",
"Kaneva",
"Kru",
"Kuma Reality",
"Kung Fu Factory",
"Laminar Research",
"Lazy 8",
"Left Field",
"Legacy",
"Leland",
"Lightspeed LA",
"Limbic",
"Limited Run",
"LJN",
"Lock 'n Load Publishing",
"The Logic Factory",
"Lucky Chicken",
"Machine Zone",
"MacPlay",
"Magic Pixel",
"Majesco",
"Manifesto",
"Mass Media",
"Mastiff",
"Matrix",
"Media Vision",
"Mega Cat",
"Mentez",
"MetaArcade",
"Meteor",
"Microsoft",
"MidBoss",
"Mightier",
"Mighty Rabbit",
"Mikengreg",
"Mindspark Network",
"Mistwalker",
"Mobalytics",
"Mohawk",
"The Molasses Flood",
"Monolith",
"Monster",
"Motorsport",
"Mountain King",
"Movaya",
"Muse",
"Muzzy Lane",
"Naked Sky",
"Naughty Dog",
"Nerjyzed",
"Nerve",
"NetherRealm",
"New World",
"Night Light",
"Nightdive",
"NimbleBit",
"Nintendo",
"Novel",
"NTN Buzztime",
"Nyko",
"Oasys Mobile",
"Obsidian",
"The Odd Gentlemen",
"OeFun",
"The Omni Group",
"Open Network",
"Other Ocean",
"OtherSide",
"Owlchemy Labs",
"Oxide",
"Pangea",
"Panic",
"Paragon",
"Paramount Digital",
"Persuasive",
"Piko",
"Pinkerton Road",
"Pipeworks",
"Piranha Publishing",
"Pixel Press",
"Pixelberry",
"PixelJAM",
"Pixelopus",
"Playdek",
"PlayMotion",
"Polyarc",
"PowerA",
"Private Division",
"Proletariat",
"Psyonix",
"Punch",
"Puppet Combo",
"PVP Live",
"Quicksilver",
"RAD Game Tools",
"Radiant",
"Rainbow",
"Ratloop",
"Raven",
"Raw Thrills",
"Re-Logic",
"Ready at Dawn",
"Realtime Associates",
"Reaxion",
"Red Storm",
"Redbana",
"Relentless",
"Ripcord",
"Robot",
"RockLive",
"Rockstar",
"Rockstar New England",
"Rogue Rocket",
"Running with Scissors",
"Saber",
"Sakevisual",
"Sandlot",
"Schell",
"Sega",
"Sekai Project",
"Sekretagent",
"Serellan",
"Serenity Forge",
"Seven Lights",
"Seven45",
"Signal",
"Silver Creek",
"Simutronics",
"Ska",
"Skybound",
"SmartCell",
"Smule",
"Snail",
"Snowblind",
"Soldak",
"Soma",
"Sony",
"Soup2Nuts",
"Specular",
"Spiderweb",
"Sports Mogul",
"Spry Fox",
"Stardock",
"Stern",
"Storm8",
"Studio FOW",
"Studio Wildcard",
"Subatomic",
"Sucker Punch",
"Sumerian Comics",
"Sunstorm",
"Super Fighter Team",
"Supergiant",
"SuperVillain",
"Surreal",
"Take-Two",
"Tapinator",
"Telegames",
"Third Wire",
"Tiger Style",
"Tigon",
"Tilted Mill",
"Tilting Point",
"TinyBuild",
"TinyCo",
"Tommo",
"Tornado",
"Torpex",
"Tri Synergy",
"Trilobyte",
"Trion Worlds",
"Tripwire",
"Turn 10",
"UFO",
"Umbrella",
"Undead Labs",
"Unisonic",
"Unknown Worlds",
"Urban Brain",
"Valcon",
"Valve",
"Vector Unit",
"Velan",
"Venan",
"Victory",
"Avalon Hill",
"Vid Kidz",
"Virtual Heroes",
"Wadjet Eye",
"Wahoo",
"Wargaming Chicago-Baltimore",
"WayForward",
"WB Boston",
"WB New York",
"Webfoot Technologies",
"The Whole Experience",
"Wild Shadow",
"WildTangent",
"WildWorks",
"Windward",
"Winged Cloud",
"Wisdom Tree",
"WisdomTools Enterprises",
"WMS Industries",
"World's Edge",
"Wraith",
"Xbox Game",
"XS",
"Xseed",
"Xsolla",
"Yacht Club",
"YNK",
"Z2",
"Zachtronics",
"Zeboyd",
"ZeniMax Online",
"Zojoi",
"Zynga",
"Zynga Eugene",
"Zynga with Friends",
