#pragma once

#define MQMAIN_VERSION_MAJOR 3
#define MQMAIN_VERSION_MINOR 0
#define MQMAIN_VERSION_REV   0
#define MQMAIN_VERSION_BUILD 0

#define MQMAIN_GIT_HASH "nohash"

#define STRINGIFY_MACRO_(x) #x
#define STRINGIFY_MACRO(x) STRINGIFY_MACRO_(x)

#define MQMAIN_VERSION STRINGIFY_MACRO(MQMAIN_VERSION_MAJOR) "." STRINGIFY_MACRO(MQMAIN_VERSION_MINOR) "." STRINGIFY_MACRO(MQMAIN_VERSION_REV) "." STRINGIFY_MACRO(MQMAIN_VERSION_BUILD)
