#pragma once

// abseil (protobuf dependency)
#pragma comment(lib, "absl_base")
#pragma comment(lib, "absl_borrowed_fixup_buffer")
#pragma comment(lib, "absl_city")
#pragma comment(lib, "absl_civil_time")
#pragma comment(lib, "absl_cord")
#pragma comment(lib, "absl_cord_internal")
#pragma comment(lib, "absl_cordz_functions")
#pragma comment(lib, "absl_cordz_handle")
#pragma comment(lib, "absl_cordz_info")
#pragma comment(lib, "absl_cordz_sample_token")
#pragma comment(lib, "absl_crc32c")
#pragma comment(lib, "absl_crc_cord_state")
#pragma comment(lib, "absl_crc_cpu_detect")
#pragma comment(lib, "absl_crc_internal")
#pragma comment(lib, "absl_debugging_internal")
#pragma comment(lib, "absl_decode_rust_punycode")
#pragma comment(lib, "absl_demangle_internal")
#pragma comment(lib, "absl_demangle_rust")
#pragma comment(lib, "absl_die_if_null")
#pragma comment(lib, "absl_examine_stack")
#pragma comment(lib, "absl_exponential_biased")
#pragma comment(lib, "absl_failure_signal_handler")
#pragma comment(lib, "absl_flags_commandlineflag")
#pragma comment(lib, "absl_flags_commandlineflag_internal")
#pragma comment(lib, "absl_flags_config")
#pragma comment(lib, "absl_flags_internal")
#pragma comment(lib, "absl_flags_marshalling")
#pragma comment(lib, "absl_flags_parse")
#pragma comment(lib, "absl_flags_private_handle_accessor")
#pragma comment(lib, "absl_flags_program_name")
#pragma comment(lib, "absl_flags_reflection")
#pragma comment(lib, "absl_flags_usage")
#pragma comment(lib, "absl_flags_usage_internal")
#pragma comment(lib, "absl_generic_printer_internal")
#pragma comment(lib, "absl_graphcycles_internal")
#pragma comment(lib, "absl_hash")
#pragma comment(lib, "absl_hashtable_profiler")
#pragma comment(lib, "absl_hashtablez_sampler")
#pragma comment(lib, "absl_int128")
#pragma comment(lib, "absl_kernel_timeout_internal")
#pragma comment(lib, "absl_leak_check")
#pragma comment(lib, "absl_log_entry")
#pragma comment(lib, "absl_log_flags")
#pragma comment(lib, "absl_log_globals")
#pragma comment(lib, "absl_log_initialize")
#pragma comment(lib, "absl_log_internal_check_op")
#pragma comment(lib, "absl_log_internal_conditions")
#pragma comment(lib, "absl_log_internal_fnmatch")
#pragma comment(lib, "absl_log_internal_format")
#pragma comment(lib, "absl_log_internal_globals")
#pragma comment(lib, "absl_log_internal_log_sink_set")
#pragma comment(lib, "absl_log_internal_message")
#pragma comment(lib, "absl_log_internal_nullguard")
#pragma comment(lib, "absl_log_internal_proto")
#pragma comment(lib, "absl_log_internal_structured_proto")
#pragma comment(lib, "absl_log_severity")
#pragma comment(lib, "absl_log_sink")
#pragma comment(lib, "absl_malloc_internal")
#pragma comment(lib, "absl_periodic_sampler")
#pragma comment(lib, "absl_poison")
#pragma comment(lib, "absl_profile_builder")
#pragma comment(lib, "absl_random_distributions")
#pragma comment(lib, "absl_random_internal_distribution_test_util")
#pragma comment(lib, "absl_random_internal_entropy_pool")
#pragma comment(lib, "absl_random_internal_platform")
#pragma comment(lib, "absl_random_internal_randen")
#pragma comment(lib, "absl_random_internal_randen_hwaes")
#pragma comment(lib, "absl_random_internal_randen_hwaes_impl")
#pragma comment(lib, "absl_random_internal_randen_slow")
#pragma comment(lib, "absl_random_internal_seed_material")
#pragma comment(lib, "absl_random_seed_gen_exception")
#pragma comment(lib, "absl_random_seed_sequences")
#pragma comment(lib, "absl_raw_hash_set")
#pragma comment(lib, "absl_raw_logging_internal")
#pragma comment(lib, "absl_scoped_set_env")
#pragma comment(lib, "absl_spinlock_wait")
#pragma comment(lib, "absl_stacktrace")
#pragma comment(lib, "absl_status")
#pragma comment(lib, "absl_statusor")
#pragma comment(lib, "absl_str_format_internal")
#pragma comment(lib, "absl_strerror")
#pragma comment(lib, "absl_strings")
#pragma comment(lib, "absl_strings_internal")
#pragma comment(lib, "absl_symbolize")
#pragma comment(lib, "absl_synchronization")
#pragma comment(lib, "absl_throw_delegate")
#pragma comment(lib, "absl_time")
#pragma comment(lib, "absl_time_zone")
#pragma comment(lib, "absl_tracing_internal")
#pragma comment(lib, "absl_utf8_for_code_point")
#pragma comment(lib, "absl_vlog_config_internal")

// utf8 (protobuf/abseil dependency)
#pragma comment(lib, "utf8_range")
#pragma comment(lib, "utf8_validity")

// protobuf
#ifdef _DEBUG
    #pragma comment(lib, "libprotobufd")
#else
    #pragma comment(lib, "libprotobuf")
#endif
