;---------------------------------------------------------------------------------------
; These definitions exist to completely bypass the code generated by the compiler. Be sure
; To also include any of these exported symbols in AssemblyFunctions.def so that they are
; exported in the dll.

extern _CXWnd__CXWnd
extern _CSidlScreenWnd__CSidlScreenWnd1
extern _CSidlScreenWnd__CSidlScreenWnd2

section .text

; public: __thiscall eqlib::CXWnd::CXWnd(class eqlib::CXWnd *,unsigned int,struct eqlib::CXRect)"
global ??0CXWnd@eqlib@@QAE@PAV01@IUCXRect@1@@Z
??0CXWnd@eqlib@@QAE@PAV01@IUCXRect@1@@Z:
	mov eax, [_CXWnd__CXWnd]
	jmp eax

;---------------------------------------------------------------------------------------

; public: __thiscall eqlib::CSidlScreenWnd::CSidlScreenWnd(class eqlib::CXWnd *,class eqlib::CXStr const &)"
global ??0CSidlScreenWnd@eqlib@@QAE@PAVCXWnd@1@ABVCXStr@1@@Z
??0CSidlScreenWnd@eqlib@@QAE@PAVCXWnd@1@ABVCXStr@1@@Z:
	mov eax, [_CSidlScreenWnd__CSidlScreenWnd2]
	jmp eax

;---------------------------------------------------------------------------------------

; public: __thiscall eqlib::CSidlScreenWnd::CSidlScreenWnd(class eqlib::CXWnd *,class eqlib::CXStr const &,int,int,char *)
global ??0CSidlScreenWnd@eqlib@@QAE@PAVCXWnd@1@ABVCXStr@1@HHPAD@Z
??0CSidlScreenWnd@eqlib@@QAE@PAVCXWnd@1@ABVCXStr@1@HHPAD@Z:
	mov eax, [_CSidlScreenWnd__CSidlScreenWnd1]
	jmp eax
