;---------------------------------------------------------------------------------------
; These definitions exist to completely bypass the code generated by the compiler. Be sure
; To also include any of these exported symbols in AssemblyFunctions.def so that they are
; exported in the dll.

extern _CXWnd__CXWnd
extern _CXWnd__dCXWnd
extern _CSidlScreenWnd__CSidlScreenWnd1
extern _CSidlScreenWnd__CSidlScreenWnd2
extern _CSidlScreenWnd__dCSidlScreenWnd
extern _MapViewMap__MapViewMap
extern _MapViewMap__dMapViewMap
extern _ItemClient__ItemClient
extern _ItemClient__dItemClient

section .text

; public: __thiscall eqlib::CXWnd::CXWnd(class eqlib::CXWnd *,unsigned int,struct eqlib::CXRect)"
global ??0CXWnd@eqlib@@QAE@PAV01@IUCXRect@1@@Z
??0CXWnd@eqlib@@QAE@PAV01@IUCXRect@1@@Z:
	mov eax, [_CXWnd__CXWnd]
	jmp eax

;---------------------------------------------------------------------------------------

; public: virtual __thiscall eqlib::CXWnd::~CXWnd(void) proc near
global ??1CXWnd@eqlib@@UAE@XZ
??1CXWnd@eqlib@@UAE@XZ:
	mov eax, [_CXWnd__dCXWnd]
	jmp eax

;---------------------------------------------------------------------------------------

; public: __thiscall eqlib::CSidlScreenWnd::CSidlScreenWnd(class eqlib::CXWnd *,class eqlib::CXStr const &)"
global ??0CSidlScreenWnd@eqlib@@QAE@PAVCXWnd@1@ABVCXStr@1@@Z
??0CSidlScreenWnd@eqlib@@QAE@PAVCXWnd@1@ABVCXStr@1@@Z:
	mov eax, [_CSidlScreenWnd__CSidlScreenWnd2]
	jmp eax

;---------------------------------------------------------------------------------------

; public: __thiscall eqlib::CSidlScreenWnd::CSidlScreenWnd(class eqlib::CXWnd *,class eqlib::CXStr const &,int,int,char *)
global ??0CSidlScreenWnd@eqlib@@QAE@PAVCXWnd@1@ABVCXStr@1@HHPAD@Z
??0CSidlScreenWnd@eqlib@@QAE@PAVCXWnd@1@ABVCXStr@1@HHPAD@Z:
	mov eax, [_CSidlScreenWnd__CSidlScreenWnd1]
	jmp eax


;---------------------------------------------------------------------------------------

; public: virtual __thiscall eqlib::CSidlScreenWnd::~CSidlScreenWnd(void) proc near
global ??1CSidlScreenWnd@eqlib@@UAE@XZ
??1CSidlScreenWnd@eqlib@@UAE@XZ:
	mov eax, [_CSidlScreenWnd__dCSidlScreenWnd]
	jmp eax

;---------------------------------------------------------------------------------------

; public: __thiscall eqlib::MapViewMap::MapViewMap(eqlib::MapViewMap *__hidden this)
global ??0MapViewMap@eqlib@@QAE@XZ
??0MapViewMap@eqlib@@QAE@XZ:
	mov eax, [_MapViewMap__MapViewMap]
	jmp eax

;---------------------------------------------------------------------------------------

; void __thiscall eqlib::MapViewMap::~MapViewMap(eqlib::MapViewMap *__hidden this)
global ??1MapViewMap@eqlib@@UAE@XZ
??1MapViewMap@eqlib@@UAE@XZ:
	mov eax, [_MapViewMap__dMapViewMap]
	jmp eax

;---------------------------------------------------------------------------------------

; public: __thiscall eqlib::CONTENTS::CONTENTS(eqlib::CONTENTS *__hidden this)
global ??0CONTENTS@eqlib@@QAE@XZ
??0CONTENTS@eqlib@@QAE@XZ:
	mov eax, [_ItemClient__ItemClient]
	jmp eax

;---------------------------------------------------------------------------------------

; void __thiscall eqlib::CONTENTS::~CONTENTS(eqlib::CONTENTS *__hidden this)
global ??1CONTENTS@eqlib@@UAE@XZ:
??1CONTENTS@eqlib@@UAE@XZ:
	mov eax, [_ItemClient__dItemClient]
	jmp eax
