name: Build MacroQuest Live Release

on:
  push:
    tags:
      - rel-live

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  call_build:
    uses: ./.github/workflows/build_release_shared.yaml
    with:
      client_target: live
    secrets: inherit