name: Build Custom MacroQuest Live

on:
  push:
    branches:
      - custom-release
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  call_build:
    uses: ./.github/workflows/build_custom_shared.yaml
    with:
      client_target: live
      resource_id: ${{ vars.REDGUIDES_RESOURCE_ID_LIVE }}
    secrets: inherit
