name: Build MacroQuest Release

on:
  push:
    branches:
      - emu

jobs:
  build:
    runs-on: [windows-2022]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: emu
          submodules: recursive
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Build
        shell: pwsh
        run: msbuild src/MacroQuest.sln
      - uses: actions/upload-artifact@v3
        with:
          name: MacroQuest
          path: D:\a\macroquest\macroquest\build\bin\debug\*
        
