name: CI Emu

on:
  push:
    branches:
      - master
    tags-ignore:
      - rel-*

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  call_build:
    uses: ./.github/workflows/ci_shared.yaml
    with:
      client_target: emu
    secrets: inherit